name: "Build"
on:
workflow_dispatch:
pull_request:
  branches:
    - master
  push:
  branches:
    - master
jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     id-token: write
   steps:
   - uses: actions/checkout@v4
   - uses: DeterminateSystems/nix-installer-action@main
   - uses: DeterminateSystems/magic-nix-cache-action@main
   - run: nix flake check --print-build-logs --keep-going
  check-no-default-features:
    uses: ./.github/actions/rust-env
    steps:
    - run: cargo check --no-default-features
  check-debug-feature:
    uses: ./.github/actions/rust-env
    steps:
    - run: cargo check --features debug
  check-profile-with-tracy-feature:
    uses: ./.github/actions/rust-env
    steps:
    - run: cargo check --features profile-with-tracy
